Document: ip-scan
Title: Debian ip-scan Manual
Author: <insert document author here>
Abstract: This manual describes what ip-scan is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ip-scan/ip-scan.sgml.gz

Format: postscript
Files: /usr/share/doc/ip-scan/ip-scan.ps.gz

Format: text
Files: /usr/share/doc/ip-scan/ip-scan.text.gz

Format: HTML
Index: /usr/share/doc/ip-scan/html/index.html
Files: /usr/share/doc/ip-scan/html/*.html
